import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "doc",
      id: "intro",
      label: "iyibir WMS Nedir?",
    },
    {
      type: "category",
      label: "🚀 Genel Bakış",
      collapsible: true,
      collapsed: false,
      items: [
        { type: "doc", id: "giris/index", label: "Hızlı Başlangıç" },
        { type: "doc", id: "giris/sistem-gereksinimleri", label: "Sistem Gereksinimleri" },
        { type: "doc", id: "giris/surum-notlari", label: "Sürüm Notları" },
      ],
    },
    {
      type: "category",
      label: "🔧 Kurulum & Yapılandırma",
      collapsible: true,
      collapsed: true,
      items: [
        { type: "doc", id: "kurulum/index", label: "Genel Bakış" },
        { type: "doc", id: "kurulum/windows-server-iis", label: "Windows Server & IIS" },
        { type: "doc", id: "kurulum/sql-server", label: "SQL Server Kurulumu" },
        { type: "doc", id: "kurulum/logo-tiger-entegrasyon", label: "Logo Tiger Entegrasyonu" },
        { type: "doc", id: "kurulum/kullanici-roller", label: "Kullanıcı & Roller" },
        { type: "doc", id: "kurulum/depo-lokasyon-yapilandirma", label: "Depo & Lokasyon" },
      ],
    },
    {
      type: "category",
      label: "📱 Mobil Uygulama",
      collapsible: true,
      collapsed: true,
      items: [
        { type: "doc", id: "mobil-uygulama/index", label: "Genel Bakış" },
        { type: "doc", id: "mobil-uygulama/indirme-giris", label: "İndirme & Giriş" },
        { type: "doc", id: "mobil-uygulama/ana-ekran", label: "Ana Ekran" },
        { type: "doc", id: "mobil-uygulama/barkod-tarama", label: "Barkod Tarama" },
        { type: "doc", id: "mobil-uygulama/offline-mod", label: "Offline Mod" },
      ],
    },
    {
      type: "category",
      label: "🌐 Web Arayüzü",
      collapsible: true,
      collapsed: true,
      items: [
        { type: "doc", id: "web-arayuzu/index", label: "Genel Bakış" },
        { type: "doc", id: "web-arayuzu/dashboard", label: "Dashboard" },
        { type: "doc", id: "web-arayuzu/raporlar", label: "Raporlar" },
        { type: "doc", id: "web-arayuzu/yonetim-paneli", label: "Yönetim Paneli" },
      ],
    },
    {
      type: "category",
      label: "📦 Operasyonlar",
      collapsible: true,
      collapsed: false,
      items: [
        { type: "doc", id: "operasyonlar/index", label: "Genel Bakış" },
        {
          type: "category",
          label: "Mal Kabul",
          collapsible: true,
          collapsed: false,
          items: [
            { type: "doc", id: "operasyonlar/mal-kabul/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/mal-kabul/serbest-mal-kabul", label: "Serbest Mal Kabul" },
            { type: "doc", id: "operasyonlar/mal-kabul/siparise-bagli", label: "Siparişe Bağlı Kabul" },
            { type: "doc", id: "operasyonlar/mal-kabul/iade-kabul", label: "İade Kabul" },
            { type: "doc", id: "operasyonlar/mal-kabul/irsaliye-iadesi", label: "İrsaliye İadesi" },
          ],
        },
        {
          type: "category",
          label: "Malzeme",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", id: "operasyonlar/malzeme/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/malzeme/giris", label: "Malzeme Giriş" },
            { type: "doc", id: "operasyonlar/malzeme/cikis", label: "Malzeme Çıkış" },
            { type: "doc", id: "operasyonlar/malzeme/transfer", label: "Transfer" },
            { type: "doc", id: "operasyonlar/malzeme/lot-islemleri", label: "Lot İşlemleri" },
          ],
        },
        {
          type: "category",
          label: "Sevkiyat",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", id: "operasyonlar/sevkiyat/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/sevkiyat/serbest-sevkiyat", label: "Serbest Sevkiyat" },
            { type: "doc", id: "operasyonlar/sevkiyat/siparis-toplama", label: "Sipariş Toplama" },
            { type: "doc", id: "operasyonlar/sevkiyat/sevkiyat-transferi", label: "Sevkiyat Transferi" },
            { type: "doc", id: "operasyonlar/sevkiyat/iade-sevkiyat", label: "İade Sevkiyat" },
          ],
        },
        {
          type: "category",
          label: "Sayım",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", id: "operasyonlar/sayim/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/sayim/depo-sayimi", label: "Depo Sayımı" },
            { type: "doc", id: "operasyonlar/sayim/lokasyon-sayimi", label: "Lokasyon Sayımı" },
            { type: "doc", id: "operasyonlar/sayim/urun-sayimi", label: "Ürün Sayımı" },
          ],
        },
        {
          type: "category",
          label: "Üretim",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", id: "operasyonlar/uretim/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/uretim/uretim-emri", label: "Üretim Emri İşleme" },
            { type: "doc", id: "operasyonlar/uretim/hizli-uretim", label: "Hızlı Üretim" },
            { type: "doc", id: "operasyonlar/uretim/yeniden-isleme", label: "Yeniden İşleme" },
          ],
        },
        {
          type: "category",
          label: "Fason",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", id: "operasyonlar/fason/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/fason/fason-cikis", label: "Fason Çıkış" },
            { type: "doc", id: "operasyonlar/fason/fason-kabul", label: "Fason Kabul" },
            { type: "doc", id: "operasyonlar/fason/fason-transfer", label: "Fason Transfer" },
            { type: "doc", id: "operasyonlar/fason/fason-uretim", label: "Fason Üretim" },
          ],
        },
        {
          type: "category",
          label: "Talep",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", id: "operasyonlar/talep/index", label: "Genel Bakış" },
            { type: "doc", id: "operasyonlar/talep/talep-olustur", label: "Talep Oluştur" },
            { type: "doc", id: "operasyonlar/talep/talep-karsila", label: "Talep Karşıla" },
            { type: "doc", id: "operasyonlar/talep/bekleyen-talepler", label: "Bekleyen Talepler" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🤖 AI Agentler",
      collapsible: true,
      collapsed: true,
      items: [
        { type: "doc", id: "ai-agentler/index", label: "Genel Bakış & MCP" },
        { type: "doc", id: "ai-agentler/stok-uzmani", label: "Stok Uzmanı" },
        { type: "doc", id: "ai-agentler/satis-uzmani", label: "Satış Uzmanı" },
        { type: "doc", id: "ai-agentler/satin-alma-uzmani", label: "Satın Alma Uzmanı" },
        { type: "doc", id: "ai-agentler/uretim-uzmani", label: "Üretim Uzmanı" },
        { type: "doc", id: "ai-agentler/talep-uzmani", label: "Talep Uzmanı" },
        { type: "doc", id: "ai-agentler/sayim-uzmani", label: "Sayım Uzmanı" },
        { type: "doc", id: "ai-agentler/fason-uzmani", label: "Fason Uzmanı" },
      ],
    },
    {
      type: "category",
      label: "⚙️ Yönetim",
      collapsible: true,
      collapsed: true,
      items: [
        { type: "doc", id: "yonetim/index", label: "Genel Bakış" },
        { type: "doc", id: "yonetim/kullanici-yonetimi", label: "Kullanıcı Yönetimi" },
        { type: "doc", id: "yonetim/yetki-matrisi", label: "Yetki Matrisi" },
        { type: "doc", id: "yonetim/barkod-sablonlari", label: "Barkod Şablonları" },
        { type: "doc", id: "yonetim/bildirim-ayarlari", label: "Bildirim Ayarları" },
      ],
    },
    {
      type: "category",
      label: "📊 Raporlar",
      collapsible: true,
      collapsed: true,
      items: [
        { type: "doc", id: "raporlar/index", label: "Genel Bakış" },
        { type: "doc", id: "raporlar/stok-raporlari", label: "Stok Raporları" },
        { type: "doc", id: "raporlar/hareket-raporlari", label: "Hareket Raporları" },
      ],
    },
  ],
};

export default sidebars;
